### ISSUE TITLE
org-publish was supercedet by  ox-publish

### ISSUE THREAD

**Issue by tarsius** [mattfidler/Emacs-Speaks-NONMEM#29]
While investigating feature inconsistencies as part of my work on the Emacsmirror, I noticed that `esn-doc.el.gz` requires `org-publish`. That library was superseded by `ox-publish`. Unless you want to stick to some old version of Org, I think you should adjust the dependency. Thanks!

**Comment by mattfidler** [comment]
Thanks.  I sort of use this for my own work;  Its full of bugs and I haven't fixed them.  This is probably one of them.
